services:
    postgres:
        image: postgres:15
        container_name: database_tp1_golang
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${CONTAINER_PORT}:${DB_PORT}"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init:/docker-entrypoint-initdb.d

volumes:
    postgres_data: